# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Manga-Anime_searcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Manga-Anime_searcher
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'lottie-ios'
  pod 'SkeletonView'
  pod 'Parse'
  pod 'MessageInputBar'

  target 'Manga-Anime_searcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Manga-Anime_searcherUITests' do
    # Pods for testing
  end

end
